-- ==============================================================================
-- AUDITORIAPLUS+ DATABASE SCHEMA & REALTIME CONFIGURATION (SUPABASE / POSTGRES)
-- ==============================================================================

-- 1. Tabla de Tareas de Misión de Auditoría (Read_Mission_Tasks)
CREATE TABLE IF NOT EXISTS public."Read_Mission_Tasks" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "MissionId" VARCHAR(100) NOT NULL,
    "SkuCode" VARCHAR(100) NOT NULL,
    "DepositCode" VARCHAR(50) NOT NULL,
    "Status" VARCHAR(30) NOT NULL DEFAULT 'Pending_Count' 
        CHECK ("Status" IN ('Pending_Count', 'Counting', 'Counted', 'Discrepancy', 'Reconciled', 'Cancelled')),
    
    -- Teóricos obtenidos desde MaraPlus ERP vía Relay Agent
    "SystemQuantity" NUMERIC DEFAULT NULL,          -- stock_quantity
    "SalesDuringAudit" NUMERIC DEFAULT 0,           -- ventas_del_dia / ventas_dia
    
    -- Conteo físico en terreno
    "CountedQuantity" NUMERIC DEFAULT NULL,         -- Unidades contadas por el auditor
    "Discrepancy" NUMERIC GENERATED ALWAYS AS (
        CASE 
            WHEN "CountedQuantity" IS NOT NULL AND "SystemQuantity" IS NOT NULL 
            THEN "CountedQuantity" - ("SystemQuantity" - COALESCE("SalesDuringAudit", 0))
            ELSE NULL 
        END
    ) STORED,

    "LastTheoreticalSyncAt" TIMESTAMPTZ DEFAULT NULL,
    "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "UpdatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Índices de alto rendimiento para búsqueda en tareas y Workers
CREATE INDEX IF NOT EXISTS idx_mission_tasks_lookup 
ON public."Read_Mission_Tasks" ("MissionId", "SkuCode", "DepositCode");

CREATE INDEX IF NOT EXISTS idx_mission_tasks_sync_candidate 
ON public."Read_Mission_Tasks" ("Status", "LastTheoreticalSyncAt")
WHERE "Status" IN ('Pending_Count', 'Counting');

-- 2. Tabla física Relay_Queue (Cola FIFO Realtime para On-Premise Relay Agent)
CREATE TABLE IF NOT EXISTS public."Relay_Queue" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SkuCode" VARCHAR(100) NOT NULL,
    "DepositCode" VARCHAR(50) DEFAULT 'DEFAULT',
    "Status" VARCHAR(20) NOT NULL DEFAULT 'Pending' 
        CHECK ("Status" IN ('Pending', 'Processing', 'Completed', 'Failed')),
    "MissionTaskId" BIGINT REFERENCES public."Read_Mission_Tasks"("Id") ON DELETE SET NULL,
    "MissionId" VARCHAR(100) DEFAULT NULL,
    "Payload" JSONB DEFAULT NULL,
    "StockQuantity" NUMERIC DEFAULT NULL,
    "VentasDelDia" NUMERIC DEFAULT NULL,
    "ErrorMessage" TEXT DEFAULT NULL,
    "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "ProcessedAt" TIMESTAMPTZ DEFAULT NULL
);

CREATE INDEX IF NOT EXISTS idx_relay_queue_fifo 
ON public."Relay_Queue" ("Status", "CreatedAt" ASC);

-- 3. Tabla de Transferencias Virtuales y Compensaciones (Read_Virtual_Transfers)
-- Implementa el Nodo de Tránsito Virtual (150104)
CREATE TABLE IF NOT EXISTS public."Read_Virtual_Transfers" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "MissionId" VARCHAR(100) NOT NULL,
    "SkuCode" VARCHAR(100) NOT NULL,
    "FromDeposit" VARCHAR(50) NOT NULL,             -- Depósito con sobrante (+), ej. 150103
    "ToDeposit" VARCHAR(50) NOT NULL,               -- Depósito con faltante (-), ej. 150101
    "TransitDeposit" VARCHAR(50) NOT NULL DEFAULT '150104', -- Nodo de Tránsito Virtual
    "QuantityToMove" NUMERIC NOT NULL CHECK ("QuantityToMove" > 0),
    "Status" VARCHAR(30) NOT NULL DEFAULT 'Suggested' 
        CHECK ("Status" IN ('Suggested', 'Approved', 'Rejected', 'Pending_ERP_Sync', 'Applied_ERP', 'Failed_ERP')),
    "SurplusBefore" NUMERIC NOT NULL,
    "DeficitBefore" NUMERIC NOT NULL,
    "ErpDocumentRef" VARCHAR(100) DEFAULT NULL,     -- Número de traspaso MaraPlus (ej: TRF-2026-091)
    "Notes" TEXT DEFAULT NULL,
    "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "AppliedAt" TIMESTAMPTZ DEFAULT NULL
);

CREATE INDEX IF NOT EXISTS idx_virtual_transfers_mission_sku 
ON public."Read_Virtual_Transfers" ("MissionId", "SkuCode", "Status");

-- 4. Habilitar Replicación Realtime en Supabase para Relay_Queue
ALTER PUBLICATION supabase_realtime ADD TABLE public."Relay_Queue";
ALTER PUBLICATION supabase_realtime ADD TABLE public."Read_Virtual_Transfers";
ALTER PUBLICATION supabase_realtime ADD TABLE public."Read_Mission_Tasks";

-- 5. Row Level Security (RLS)
ALTER TABLE public."Read_Mission_Tasks" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Relay_Queue" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Read_Virtual_Transfers" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Service Role Full Access Tasks" ON public."Read_Mission_Tasks" FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Service Role Full Access Relay" ON public."Relay_Queue" FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Service Role Full Access Transfers" ON public."Read_Virtual_Transfers" FOR ALL TO service_role USING (true) WITH CHECK (true);

-- Lectura para usuarios autenticados
CREATE POLICY "Authenticated Users Read Tasks" ON public."Read_Mission_Tasks" FOR SELECT TO authenticated USING (true);
CREATE POLICY "Authenticated Users Read Transfers" ON public."Read_Virtual_Transfers" FOR SELECT TO authenticated USING (true);

-- 6. Inserción de Datos Demo para Prueba Inmediata
-- Ejemplo del caso solicitado: Almacén 150101 con faltante -5 y Piso 150103 con sobrante +6
INSERT INTO public."Read_Mission_Tasks" 
("MissionId", "SkuCode", "DepositCode", "Status", "SystemQuantity", "SalesDuringAudit", "CountedQuantity")
VALUES
('MIS-2026-VAL-01', '759103100245', '150101', 'Counted', 50, 0, 45), -- Faltante: 45 - 50 = -5 unidades
('MIS-2026-VAL-01', '759103100245', '150103', 'Counted', 20, 2, 24), -- Teórico ajustado = 18; Conteo = 24 -> Sobrante: +6 unidades
('MIS-2026-VAL-01', '759204200889', '150101', 'Pending_Count', NULL, 0, NULL),
('MIS-2026-VAL-01', '759204200889', '150103', 'Pending_Count', NULL, 0, NULL)
ON CONFLICT DO NOTHING;
