-- ==============================================================================
-- MaraPlus Relay Queue - Supabase PostgreSQL Schema
-- ==============================================================================
-- Execute this script in your Supabase SQL Editor (https://supabase.com/dashboard)
-- ==============================================================================

-- 1. Create table Relay_Queue
CREATE TABLE IF NOT EXISTS public."Relay_Queue" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SkuCode" VARCHAR(100) NOT NULL,
    "DepositCode" VARCHAR(50) DEFAULT 'DEFAULT',
    "Status" VARCHAR(20) NOT NULL DEFAULT 'Pending' CHECK ("Status" IN ('Pending', 'Processing', 'Completed', 'Failed')),
    "Payload" JSONB DEFAULT NULL,
    "StockQuantity" NUMERIC DEFAULT NULL,
    "VentasDelDia" NUMERIC DEFAULT NULL,
    "ErrorMessage" TEXT DEFAULT NULL,
    "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "ProcessedAt" TIMESTAMPTZ DEFAULT NULL
);

-- 2. Indexes for high-performance FIFO consumption
CREATE INDEX IF NOT EXISTS idx_relay_queue_status_created 
ON public."Relay_Queue" ("Status", "CreatedAt" ASC);

CREATE INDEX IF NOT EXISTS idx_relay_queue_sku 
ON public."Relay_Queue" ("SkuCode");

-- 3. CRITICAL: Enable Supabase Realtime for this table
-- This enables WebSockets broadcast for INSERT and UPDATE operations
ALTER PUBLICATION supabase_realtime ADD TABLE public."Relay_Queue";

-- 4. Enable Row Level Security (RLS)
ALTER TABLE public."Relay_Queue" ENABLE ROW LEVEL SECURITY;

-- Allow service_role key full unrestricted access (used by the On-Premise Relay Agent)
CREATE POLICY "Service Role has full access to Relay_Queue" 
ON public."Relay_Queue"
FOR ALL 
TO service_role 
USING (true) 
WITH CHECK (true);

-- (Optional) Allow authenticated web clients or frontends to insert items into the queue
CREATE POLICY "Authenticated users can enqueue inventory checks" 
ON public."Relay_Queue"
FOR INSERT 
TO authenticated 
WITH CHECK (true);

CREATE POLICY "Authenticated users can view queue items" 
ON public."Relay_Queue"
FOR SELECT 
TO authenticated 
USING (true);

-- 5. Seed sample records for immediate testing
INSERT INTO public."Relay_Queue" ("SkuCode", "DepositCode", "Status")
VALUES 
  ('PROD-1001', 'DEP-01', 'Pending'),
  ('PROD-1002', 'DEP-01', 'Pending'),
  ('PROD-1003', 'DEP-02', 'Pending')
ON CONFLICT DO NOTHING;
